### PR TITLE
Chore/bump werkzeug 3.0.3

### PR DESCRIPTION
**Pull request by george42-ctds**
JIRA ticket: [PPS-1184](https://ctds-planx.atlassian.net/browse/PPS-1184)

### Dependency updates

* werkzeug to 3.0.3
* jinja2 to 3.1.4
* cryptography to 42.0.7

### Deployment changes

[PPS-1184]: https://ctds-planx.atlassian.net/browse/PPS-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MaribelleHGomez — COMMENTED** [review]
I'm only seeing changes for the lock file?

**Comment by george42-ctds** [comment]
Yes, correct, only bumping a few dependencies in the lock file.

**Comment by MaribelleHGomez** [comment]
> Yes, correct, only bumping a few dependencies in the lock file.

so we're choosing not to change the toml file, and changing the lock file instead?

**Comment by george42-ctds** [comment]
Yes, the minimal update is to just have changes in the lock file, or do a "re-lock". The relevant packages (werkzeug, etc.) are not direct dependencies and are not listed in the pyproject.toml. The "re-locking" was sufficient to bump up these packages by a patch version or minor version. Sometimes you have to start bumping versions in the pyproject.toml to bump up sub-dependencies but that is not required in this case.

**Comment by george42-ctds** [comment]
Poetry will still utilize the pyproject.toml to determine which versions to install. Everything will still adhere to the rules in the proproject.toml.

**Review by MaribelleHGomez — APPROVED** [review]

**Pull request merged**
