### PR TITLE
test branch for Jenkins testing

### PR DESCRIPTION
**Pull request by m0nhawk**

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
Jenkins Build 7 : time taken 33 min
Check the https://jenkins.planx-pla.net/job/perf-peregrine/job/PR-122/7/display/redirect


Test results:
	Passed: 109, Failed: 0, Skipped: 0



| Test | Time (`PR`) | Time (`master`) | Diff |
| - | - | - | - |
| @ExportPerformanceTests @Performance: Export all nodes of type: case | 0.293 | 0.273 | 0.02 |
| @ExportPerformanceTests @Performance: Export all nodes of type: project | 0.083 | 0.054 | 0.03 |
| @ExportPerformanceTests @Performance: Exporting a record by ID on nodes of type: read_group | 0.083 | 0.076 | 0.01 |
| @QueryPerformanceTests @Performance: Executing bottomUp query # 0 | 0.703 | 0.624 | 0.08 |
| @QueryPerformanceTests @Performance: Executing bottomUp query # 1 | 0.565 | 0.491 | 0.07 |
| @QueryPerformanceTests @Performance: Executing bottomUp query # 2 | 0.783 | 0.469 | 0.31 |
| @QueryPerformanceTests @Performance: Executing bottomUp query # 3 | 0.679 | 0.36 | 0.32 |
| @QueryPerformanceTests @Performance: Executing bottomUp query # 4 | 0.464 | 0.338 | 0.13 |
| @QueryPerformanceTests @Performance: Executing bottomUp query # 5 | 0.299 | 0.237 | 0.06 |
| @QueryPerformanceTests @Performance: Executing bottomUp query # 6 | 0.19 | 0.139 | 0.05 |
| @QueryPerformanceTests @Performance: Executing topDown query # 0 | 0.084 | 0.06 | 0.02 |
| @QueryPerformanceTests @Performance: Executing topDown query # 1 | 0.109 | 0.074 | 0.03 |
| @QueryPerformanceTests @Performance: Executing topDown query # 2 | 0.12 | 0.092 | 0.03 |
| @QueryPerformanceTests @Performance: Executing topDown query # 3 | 0.175 | 0.15 | 0.02 |
| @QueryPerformanceTests @Performance: Executing topDown query # 4 | 0.265 | 0.225 | 0.04 |
| @QueryPerformanceTests @Performance: Executing topDown query # 5 | 0.445 | 0.29 | 0.16 |
| @QueryPerformanceTests @Performance: Executing topDown query # 6 | 0.602 | 0.435 | 0.17 |
| @QueryPerformanceTests @Performance: Executing topDown query # 7 | 0.619 | 0.477 | 0.14 |
| @SubmissionPerformanceTests @Performance: Submission aligned_reads_index 10 | 2.443 | 1.91 | 0.53 |
| @SubmissionPerformanceTests @Performance: Submission aligned_reads_index 100 | 20.657 | 17.881 | 2.78 |
| @SubmissionPerformanceTests @Performance: Submission diagnosis 10 | 0.774 | 0.381 | 0.39 |
| @SubmissionPerformanceTests @Performance: Submission experimental_metadata 10 | 2.171 | 1.778 | 0.39 |
| @SubmissionPerformanceTests @Performance: Submission experimental_metadata 100 | 19.765 | 18.239 | 1.53 |
| @SubmissionPerformanceTests @Performance: Submission exposure 10 | 0.415 | 0.395 | 0.02 |
| @SubmissionPerformanceTests @Performance: Submission exposure 100 | 3.524 | 2.887 | 0.64 |
| @SubmissionPerformanceTests @Performance: Submission family_history 10 | 0.382 | 0.335 | 0.05 |
| @SubmissionPerformanceTests @Performance: Submission keyword 10 | 0.47 | 0.35 | 0.12 |
| @SubmissionPerformanceTests @Performance: Submission read_group 10 | 0.391 | 0.364 | 0.03 |
| @SubmissionPerformanceTests @Performance: Submission read_group_qc 10 | 0.545 | 0.499 | 0.05 |
| @SubmissionPerformanceTests @Performance: Submission sample 10 | 0.509 | 0.352 | 0.16 |
| @SubmissionPerformanceTests @Performance: Submission sample 1000 | 25.416 | 0.339 | 25.08 |
| @SubmissionPerformanceTests @Performance: Submission slide 1000 | 22.425 | 0.343 | 22.08 |
| @SubmissionPerformanceTests @Performance: Submission slide_count 1000 | 21.822 | 1.863 | 19.96 |
| @SubmissionPerformanceTests @Performance: Submission slide_image 1000 | 45.109 | 2.126 | 42.98 |
| @SubmissionPerformanceTests @Performance: Submission submitted_aligned_reads 1000 | 44.901 | 1.699 | 43.20 |
| @SubmissionPerformanceTests @Performance: Submission submitted_copy_number 1000 | 45.135 | 2.344 | 42.79 |
| @SubmissionPerformanceTests @Performance: Submission submitted_methylation 1000 | 45.177 | 2.208 | 42.97 |
| @SubmissionPerformanceTests @Performance: Submission submitted_somatic_mutation 1000 | 45.1 | 1.806 | 43.29 |
| @SubmissionPerformanceTests @Performance: Submission submitted_unaligned_reads 1000 | 44.873 | 0.421 | 44.45 |

**Comment by thanh-nguyen-dang** [comment]
why this pr create too much different result? @m0nhawk

**Comment by m0nhawk** [comment]
> why this pr create too much different result? @m0nhawk

I will look into this tomorrow. 😞

**Comment by PlanXCyborg** [comment]
Jenkins Build 9 : time taken 44 min
Check the https://jenkins.planx-pla.net/job/perf-peregrine/job/PR-122/9/display/redirect


Test results:
	Passed: 109, Failed: 0, Skipped: 0



| Test | Time (`PR`) | Time (`master`) | Diff |
| - | - | - | - |
| @ExportPerformanceTests @Performance: Export all nodes of type: experiment | 0.417 | 0.368 | 0.05 |
| @ExportPerformanceTests @Performance: Export all nodes of type: project | 0.11 | 0.056 | 0.05 |
| @ExportPerformanceTests @Performance: Exporting a record by ID on nodes of type: case | 0.374 | 0.339 | 0.04 |
| @ExportPerformanceTests @Performance: Exporting a record by ID on nodes of type: experiment | 0.32 | 0.233 | 0.09 |
| @ExportPerformanceTests @Performance: Exporting a record by ID on nodes of type: read_group | 0.1 | 0.07 | 0.03 |
| @ExportPerformanceTests @Performance: Exporting a record by ID on nodes of type: read_group_qc | 0.084 | 0.075 | 0.01 |
| @SubmissionPerformanceTests @Performance: Submission acknowledgement 10 | 1.04 | 0.398 | 0.64 |
| @SubmissionPerformanceTests @Performance: Submission aligned_reads_index 10 | 2.138 | 2.033 | 0.11 |
| @SubmissionPerformanceTests @Performance: Submission case 1000 | 25.956 | 23.541 | 2.41 |
| @SubmissionPerformanceTests @Performance: Submission clinical_test 100 | 2.892 | 2.751 | 0.14 |
| @SubmissionPerformanceTests @Performance: Submission demographic 100 | 2.877 | 2.52 | 0.36 |
| @SubmissionPerformanceTests @Performance: Submission keyword 10 | 0.408 | 0.373 | 0.03 |
| @SubmissionPerformanceTests @Performance: Submission read_group 100 | 3.052 | 2.868 | 0.18 |
| @SubmissionPerformanceTests @Performance: Submission sample 1000 | 28.355 | 26.951 | 1.40 |
| @SubmissionPerformanceTests @Performance: Submission slide 10 | 0.64 | 0.608 | 0.03 |
| @SubmissionPerformanceTests @Performance: Submission slide_count 1000 | 30.054 | 24.516 | 5.54 |
| @SubmissionPerformanceTests @Performance: Submission slide_image 100 | 23.614 | 19.279 | 4.34 |
| @SubmissionPerformanceTests @Performance: Submission submitted_copy_number 10 | 2.374 | 1.968 | 0.41 |
| @SubmissionPerformanceTests @Performance: Submission submitted_copy_number 100 | 19.605 | 18.353 | 1.25 |
| @SubmissionPerformanceTests @Performance: Submission treatment 10 | 0.507 | 0.366 | 0.14 |

**Pull request closed without merging**
